version: "3.8"

services:
  backend:
    build: .
    container_name: notes-app-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: notes-app-redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    container_name: notes-app-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
