"""public parameter added to notes

Revision ID: db8f58446f94
Revises: ddc4bef16d9e
Create Date: 2025-02-03 20:24:53.809976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8f58446f94'
down_revision: Union[str, None] = 'ddc4bef16d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'public')
    # ### end Alembic commands ###
